### ISSUE TITLE
My model flies up

### ISSUE THREAD

**Issue by yili5912** [zitongbai/bipedal_control#9]
My model is lighter than h1, and it flies up when start gazebo. Which code should I change to accommodate the lighter model?

Thanks,
Yili

**Comment by zitongbai** [comment]
I have written a [readme](https://github.com/zitongbai/bipedal_control/blob/main/bipedal_robot_example/README.md) on how to implement your own robot. Hope it would be helpful :)

**Comment by yili5912** [comment]
It is fine now. urdf file issue.

Thanks!
